use crate::models::{
    AppState, HostGroup, HostNode, Preferences, ValidationIssue, ValidationSeverity, new_id,
};
use std::net::IpAddr;
use thiserror::Error;

pub const BEGIN_MARKER: &str = "# >>> Hosts Switch managed block";
pub const END_MARKER: &str = "# <<< Hosts Switch managed block";
const DEFAULT_HOSTS_PATH: &str = "/etc/hosts";

#[derive(Debug, Error)]
pub enum HostsError {
    #[error("managed block has a start marker but no end marker")]
    MissingEndMarker,
    #[error("managed block has an end marker before a start marker")]
    EndBeforeStart,
}

pub fn hosts_path() -> &'static str {
    DEFAULT_HOSTS_PATH
}

pub fn normalize_state(mut state: AppState) -> AppState {
    if state.preferences.enforce_one_active_per_group {
        for group in &mut state.groups {
            let mut found_enabled = false;
            for node in &mut group.nodes {
                if node.enabled {
                    if found_enabled {
                        node.enabled = false;
                    } else {
                        found_enabled = true;
                    }
                }
            }
        }
    }

    state
}

pub fn render_managed_block(state: &AppState) -> String {
    let mut lines = vec![
        BEGIN_MARKER.to_string(),
        "# Generated by Hosts Switch. Edit profiles in the app, not inside this block.".to_string(),
    ];

    for group in &state.groups {
        for node in group.nodes.iter().filter(|node| node.enabled) {
            let trimmed = node.content.trim();
            if trimmed.is_empty() {
                continue;
            }

            lines.push(format!("# Group: {}", group.name));
            lines.push(format!("# Node: {}", node.name));
            lines.extend(trimmed.lines().map(|line| line.trim_end().to_string()));
            lines.push(String::new());
        }
    }

    while matches!(lines.last(), Some(last) if last.is_empty()) {
        lines.pop();
    }

    lines.push(END_MARKER.to_string());
    lines.join("\n")
}

pub fn validate_state(state: &AppState) -> Vec<ValidationIssue> {
    let mut issues = Vec::new();

    for group in &state.groups {
        for node in group.nodes.iter().filter(|node| node.enabled) {
            for (index, line) in node.content.lines().enumerate() {
                if let Some(message) = validate_hosts_line(line) {
                    issues.push(ValidationIssue {
                        group_id: group.id.clone(),
                        group_name: group.name.clone(),
                        node_id: node.id.clone(),
                        node_name: node.name.clone(),
                        line_number: index + 1,
                        severity: ValidationSeverity::Error,
                        message,
                    });
                }
            }
        }
    }

    issues
}

pub fn parse_managed_block_as_state(managed_block: &str) -> AppState {
    let mut groups: Vec<HostGroup> = Vec::new();
    let mut current_group_name = "Imported".to_string();
    let mut current_node_name: Option<String> = None;
    let mut current_lines: Vec<String> = Vec::new();

    for raw_line in managed_block.lines() {
        let line = raw_line.trim_end();
        if line == BEGIN_MARKER || line == END_MARKER {
            continue;
        }
        if line == "# Generated by Hosts Switch. Edit profiles in the app, not inside this block." {
            continue;
        }
        if let Some(name) = line.strip_prefix("# Group: ") {
            push_imported_node(
                &mut groups,
                &current_group_name,
                current_node_name.take(),
                &mut current_lines,
            );
            current_group_name = name.trim().to_string();
            continue;
        }
        if let Some(name) = line.strip_prefix("# Node: ") {
            push_imported_node(
                &mut groups,
                &current_group_name,
                current_node_name.take(),
                &mut current_lines,
            );
            current_node_name = Some(name.trim().to_string());
            continue;
        }

        current_lines.push(line.to_string());
    }

    push_imported_node(
        &mut groups,
        &current_group_name,
        current_node_name.take(),
        &mut current_lines,
    );

    let enforce_one_active_per_group = groups.iter().all(|group| group.nodes.len() <= 1);

    AppState {
        version: 1,
        groups,
        preferences: Preferences {
            enforce_one_active_per_group,
            preview_on_hover: true,
            launch_at_login: false,
            enable_global_shortcut: true,
        },
    }
}

fn validate_hosts_line(line: &str) -> Option<String> {
    let trimmed = line.trim();
    if trimmed.is_empty() || trimmed.starts_with('#') {
        return None;
    }

    let tokens: Vec<&str> = trimmed
        .split_whitespace()
        .take_while(|token| !token.starts_with('#'))
        .collect();
    if tokens.len() < 2 {
        return Some("Line must contain an IP address and at least one hostname.".to_string());
    }

    if tokens[0].parse::<IpAddr>().is_err() {
        return Some("Line must start with a valid IPv4 or IPv6 address.".to_string());
    }

    for hostname in &tokens[1..] {
        if !is_valid_hostname(hostname) {
            return Some(format!(
                "Invalid hostname \"{hostname}\". Use letters, digits, dots, and hyphens."
            ));
        }
    }

    None
}

fn is_valid_hostname(hostname: &str) -> bool {
    if hostname.is_empty() || hostname.len() > 253 {
        return false;
    }
    if hostname == "localhost" {
        return true;
    }

    hostname.split('.').all(|label| {
        !label.is_empty()
            && label.len() <= 63
            && label
                .chars()
                .all(|character| character.is_ascii_alphanumeric() || character == '-')
            && label
                .chars()
                .next()
                .is_some_and(|character| character.is_ascii_alphanumeric())
            && label
                .chars()
                .last()
                .is_some_and(|character| character.is_ascii_alphanumeric())
    })
}

fn push_imported_node(
    groups: &mut Vec<HostGroup>,
    group_name: &str,
    node_name: Option<String>,
    lines: &mut Vec<String>,
) {
    let content = lines.join("\n").trim().to_string();
    lines.clear();
    if content.is_empty() {
        return;
    }

    let node = HostNode {
        id: new_id(),
        name: node_name.unwrap_or_else(|| "Imported Hosts".to_string()),
        enabled: true,
        content,
    };

    if let Some(group) = groups.iter_mut().find(|group| group.name == group_name) {
        group.nodes.push(node);
    } else {
        groups.push(HostGroup {
            id: new_id(),
            name: group_name.to_string(),
            nodes: vec![node],
        });
    }
}

pub fn merge_hosts_file(current: &str, managed_block: &str) -> Result<String, HostsError> {
    if let Some((start, end)) = managed_block_range(current)? {
        let mut merged = String::new();
        merged.push_str(current[..start].trim_end());
        if !merged.is_empty() {
            merged.push_str("\n\n");
        }
        merged.push_str(managed_block.trim());
        let suffix = current[end..].trim_start_matches(['\n', '\r']);
        if !suffix.trim().is_empty() {
            merged.push_str("\n\n");
            merged.push_str(suffix.trim_end());
        }
        merged.push('\n');
        return Ok(merged);
    }

    let mut merged = current.trim_end().to_string();
    if !merged.is_empty() {
        merged.push_str("\n\n");
    }
    merged.push_str(managed_block.trim());
    merged.push('\n');
    Ok(merged)
}

pub fn extract_managed_block(current: &str) -> Result<Option<String>, HostsError> {
    Ok(managed_block_range(current)?.map(|(start, end)| current[start..end].trim().to_string()))
}

fn managed_block_range(current: &str) -> Result<Option<(usize, usize)>, HostsError> {
    let Some(start) = current.find(BEGIN_MARKER) else {
        if current.find(END_MARKER).is_some() {
            return Err(HostsError::EndBeforeStart);
        }
        return Ok(None);
    };

    let search_after_start = start + BEGIN_MARKER.len();
    let Some(relative_end) = current[search_after_start..].find(END_MARKER) else {
        return Err(HostsError::MissingEndMarker);
    };

    let end_marker_start = search_after_start + relative_end;
    let mut end = end_marker_start + END_MARKER.len();
    let bytes = current.as_bytes();
    while end < bytes.len() && matches!(bytes[end], b'\n' | b'\r') {
        end += 1;
    }

    Ok(Some((start, end)))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::models::{AppState, HostGroup, HostNode, Preferences};

    fn test_state() -> AppState {
        AppState {
            version: 1,
            preferences: Preferences {
                enforce_one_active_per_group: true,
                preview_on_hover: true,
                launch_at_login: false,
                enable_global_shortcut: true,
            },
            groups: vec![HostGroup {
                id: "group-1".to_string(),
                name: "Development".to_string(),
                nodes: vec![
                    HostNode {
                        id: "node-1".to_string(),
                        name: "Local".to_string(),
                        enabled: true,
                        content: "127.0.0.1 api.test\n127.0.0.1 web.test".to_string(),
                    },
                    HostNode {
                        id: "node-2".to_string(),
                        name: "Remote".to_string(),
                        enabled: false,
                        content: "10.0.0.10 api.test".to_string(),
                    },
                ],
            }],
        }
    }

    #[test]
    fn renders_enabled_nodes_with_headings() {
        let rendered = render_managed_block(&test_state());

        assert!(rendered.contains(BEGIN_MARKER));
        assert!(rendered.contains("# Group: Development"));
        assert!(rendered.contains("# Node: Local"));
        assert!(rendered.contains("127.0.0.1 api.test"));
        assert!(!rendered.contains("10.0.0.10 api.test"));
        assert!(rendered.contains(END_MARKER));
    }

    #[test]
    fn appends_managed_block_without_destroying_existing_hosts() {
        let current = "127.0.0.1 localhost\n255.255.255.255 broadcasthost\n";
        let managed = render_managed_block(&test_state());
        let merged = merge_hosts_file(current, &managed).unwrap();

        assert!(merged.starts_with("127.0.0.1 localhost"));
        assert!(merged.contains("255.255.255.255 broadcasthost"));
        assert!(merged.contains(BEGIN_MARKER));
        assert!(merged.ends_with('\n'));
    }

    #[test]
    fn replaces_existing_managed_block() {
        let old = format!(
            "127.0.0.1 localhost\n\n{}\nold.example.test\n{}\n\n::1 localhost\n",
            BEGIN_MARKER, END_MARKER
        );
        let managed = render_managed_block(&test_state());
        let merged = merge_hosts_file(&old, &managed).unwrap();

        assert!(merged.contains("127.0.0.1 localhost"));
        assert!(merged.contains("::1 localhost"));
        assert!(merged.contains("127.0.0.1 api.test"));
        assert!(!merged.contains("old.example.test"));
        assert_eq!(merged.matches(BEGIN_MARKER).count(), 1);
        assert_eq!(merged.matches(END_MARKER).count(), 1);
    }

    #[test]
    fn extracts_existing_managed_block() {
        let current = format!("before\n{}\ninside\n{}\nafter\n", BEGIN_MARKER, END_MARKER);
        let extracted = extract_managed_block(&current).unwrap().unwrap();

        assert!(extracted.starts_with(BEGIN_MARKER));
        assert!(extracted.contains("inside"));
        assert!(extracted.ends_with(END_MARKER));
    }

    #[test]
    fn parses_managed_block_back_into_groups_and_nodes() {
        let block = [
            BEGIN_MARKER,
            "# Generated by Hosts Switch. Edit profiles in the app, not inside this block.",
            "# Group: Development",
            "# Node: Local",
            "127.0.0.1 api.test",
            "127.0.0.1 web.test",
            "",
            "# Group: Development",
            "# Node: Staging",
            "10.0.0.20 api.test",
            "# Group: Examples",
            "# Node: Demo",
            "93.184.216.34 example.test",
            END_MARKER,
        ]
        .join("\n");

        let state = parse_managed_block_as_state(&block);

        assert_eq!(state.groups.len(), 2);
        assert_eq!(state.groups[0].name, "Development");
        assert_eq!(state.groups[0].nodes.len(), 2);
        assert_eq!(state.groups[0].nodes[0].name, "Local");
        assert_eq!(
            state.groups[0].nodes[0].content,
            "127.0.0.1 api.test\n127.0.0.1 web.test"
        );
        assert!(state.groups[0].nodes[0].enabled);
        assert_eq!(state.groups[0].nodes[1].name, "Staging");
        assert_eq!(state.groups[1].name, "Examples");
        assert_eq!(state.groups[1].nodes[0].name, "Demo");
        assert!(!state.preferences.enforce_one_active_per_group);
    }

    #[test]
    fn keeps_one_active_preference_when_restored_groups_have_one_node_each() {
        let block = [
            BEGIN_MARKER,
            "# Group: Development",
            "# Node: Local",
            "127.0.0.1 api.test",
            "# Group: Examples",
            "# Node: Demo",
            "93.184.216.34 example.test",
            END_MARKER,
        ]
        .join("\n");

        let state = parse_managed_block_as_state(&block);

        assert!(state.preferences.enforce_one_active_per_group);
    }

    #[test]
    fn parses_legacy_managed_block_without_headings() {
        let block = format!("{BEGIN_MARKER}\n127.0.0.1 legacy.test\n{END_MARKER}");

        let state = parse_managed_block_as_state(&block);

        assert_eq!(state.groups.len(), 1);
        assert_eq!(state.groups[0].name, "Imported");
        assert_eq!(state.groups[0].nodes[0].name, "Imported Hosts");
        assert_eq!(state.groups[0].nodes[0].content, "127.0.0.1 legacy.test");
    }

    #[test]
    fn parses_empty_managed_block_as_empty_profile_list() {
        let block = format!("{BEGIN_MARKER}\n{END_MARKER}");

        let state = parse_managed_block_as_state(&block);

        assert!(state.groups.is_empty());
    }

    #[test]
    fn enforces_one_active_node_per_group() {
        let mut state = test_state();
        state.groups[0].nodes[1].enabled = true;

        let normalized = normalize_state(state);

        assert!(normalized.groups[0].nodes[0].enabled);
        assert!(!normalized.groups[0].nodes[1].enabled);
    }

    #[test]
    fn accepts_comments_blank_lines_ipv4_ipv6_and_valid_hostnames() {
        let mut state = test_state();
        state.groups[0].nodes[0].content = [
            "# comment",
            "",
            "127.0.0.1 localhost local-api.test local-api-2",
            "::1 localhost ipv6.local.test",
            "2001:db8::1 edge.example.test # inline comment",
        ]
        .join("\n");

        assert!(validate_state(&state).is_empty());
    }

    #[test]
    fn rejects_enabled_lines_without_hostname_or_valid_ip() {
        let mut state = test_state();
        state.groups[0].nodes[0].content = "127.0.0.1\n999.1.1.1 bad.test".to_string();

        let issues = validate_state(&state);

        assert_eq!(issues.len(), 2);
        assert_eq!(issues[0].line_number, 1);
        assert_eq!(
            issues[0].message,
            "Line must contain an IP address and at least one hostname."
        );
        assert_eq!(issues[1].line_number, 2);
        assert_eq!(
            issues[1].message,
            "Line must start with a valid IPv4 or IPv6 address."
        );
    }

    #[test]
    fn rejects_invalid_hostnames_only_for_enabled_nodes() {
        let mut state = test_state();
        state.groups[0].nodes[0].content = "127.0.0.1 bad_host.test".to_string();
        state.groups[0].nodes[1].content = "not-an-ip bad_host.test".to_string();

        let issues = validate_state(&state);

        assert_eq!(issues.len(), 1);
        assert_eq!(issues[0].node_id, "node-1");
        assert_eq!(
            issues[0].message,
            "Invalid hostname \"bad_host.test\". Use letters, digits, dots, and hyphens."
        );
    }
}
