import type { AppState, ValidationIssue } from "./types";

export const BEGIN_MARKER = "# >>> Hosts Switch managed block";
export const END_MARKER = "# <<< Hosts Switch managed block";

export const demoHostsFile = `##
# Host Database
#
# localhost is used to configure the loopback interface
##
127.0.0.1 localhost
255.255.255.255 broadcasthost
::1 localhost
`;

export function defaultAppState(): AppState {
  return {
    version: 1,
    groups: [
      {
        id: createId("group"),
        name: "Development",
        nodes: [
          {
            id: createId("node"),
            name: "Local API",
            enabled: false,
            content: "127.0.0.1 api.local.test\n127.0.0.1 web.local.test",
          },
          {
            id: createId("node"),
            name: "Staging API",
            enabled: false,
            content: "10.0.0.20 api.local.test\n10.0.0.21 web.local.test",
          },
        ],
      },
      {
        id: createId("group"),
        name: "Examples",
        nodes: [
          {
            id: createId("node"),
            name: "Demo Domain",
            enabled: false,
            content: "93.184.216.34 example.test",
          },
        ],
      },
    ],
    preferences: {
      enforceOneActivePerGroup: true,
      previewOnHover: true,
      launchAtLogin: false,
      enableGlobalShortcut: true,
    },
  };
}

export function normalizeState(state: AppState): AppState {
  const normalized: AppState = {
    ...state,
    preferences: {
      enforceOneActivePerGroup: state.preferences?.enforceOneActivePerGroup ?? true,
      previewOnHover: state.preferences?.previewOnHover ?? true,
      launchAtLogin: state.preferences?.launchAtLogin ?? false,
      enableGlobalShortcut: state.preferences?.enableGlobalShortcut ?? true,
    },
  };

  if (!normalized.preferences.enforceOneActivePerGroup) {
    return normalized;
  }

  return {
    ...normalized,
    groups: normalized.groups.map((group) => {
      let foundEnabled = false;
      return {
        ...group,
        nodes: group.nodes.map((node) => {
          if (!node.enabled) {
            return node;
          }
          if (foundEnabled) {
            return { ...node, enabled: false };
          }
          foundEnabled = true;
          return node;
        }),
      };
    }),
  };
}

export function renderManagedBlock(state: AppState): string {
  const lines = [
    BEGIN_MARKER,
    "# Generated by Hosts Switch. Edit profiles in the app, not inside this block.",
  ];

  for (const group of state.groups) {
    for (const node of group.nodes) {
      const content = node.content.trim();
      if (!node.enabled || content.length === 0) {
        continue;
      }
      lines.push(`# Group: ${group.name}`);
      lines.push(`# Node: ${node.name}`);
      lines.push(...content.split(/\r?\n/).map((line) => line.trimEnd()));
      lines.push("");
    }
  }

  while (lines[lines.length - 1] === "") {
    lines.pop();
  }

  lines.push(END_MARKER);
  return lines.join("\n");
}

export function validateHostsState(state: AppState): ValidationIssue[] {
  const issues: ValidationIssue[] = [];

  for (const group of state.groups) {
    for (const node of group.nodes) {
      if (!node.enabled) {
        continue;
      }

      node.content.split(/\r?\n/).forEach((line, index) => {
        const message = validateHostsLine(line);
        if (!message) {
          return;
        }

        issues.push({
          groupId: group.id,
          groupName: group.name,
          nodeId: node.id,
          nodeName: node.name,
          lineNumber: index + 1,
          severity: "error",
          message,
        });
      });
    }
  }

  return issues;
}

export function parseManagedBlockAsState(managedBlock: string): AppState {
  const groups: AppState["groups"] = [];
  let currentGroupName = "Imported";
  let currentNodeName: string | null = null;
  let currentLines: string[] = [];

  for (const rawLine of managedBlock.split(/\r?\n/)) {
    const line = rawLine.trimEnd();
    if (line === BEGIN_MARKER || line === END_MARKER) {
      continue;
    }
    if (line === "# Generated by Hosts Switch. Edit profiles in the app, not inside this block.") {
      continue;
    }
    if (line.startsWith("# Group: ")) {
      pushImportedNode(groups, currentGroupName, currentNodeName, currentLines);
      currentLines = [];
      currentNodeName = null;
      currentGroupName = line.slice("# Group: ".length).trim();
      continue;
    }
    if (line.startsWith("# Node: ")) {
      pushImportedNode(groups, currentGroupName, currentNodeName, currentLines);
      currentLines = [];
      currentNodeName = line.slice("# Node: ".length).trim();
      continue;
    }

    currentLines.push(line);
  }

  pushImportedNode(groups, currentGroupName, currentNodeName, currentLines);

  return {
    version: 1,
    groups,
    preferences: {
      enforceOneActivePerGroup: groups.every((group) => group.nodes.length <= 1),
      previewOnHover: true,
      launchAtLogin: false,
      enableGlobalShortcut: true,
    },
  };
}

export function mergeHostsFile(current: string, managedBlock: string): string {
  const range = managedBlockRange(current);
  if (range) {
    const prefix = current.slice(0, range.start).trimEnd();
    const suffix = current.slice(range.end).replace(/^[\r\n]+/, "").trimEnd();
    return [
      prefix,
      managedBlock.trim(),
      suffix,
    ].filter(Boolean).join("\n\n") + "\n";
  }

  return [current.trimEnd(), managedBlock.trim()].filter(Boolean).join("\n\n") + "\n";
}

export function extractManagedBlock(current: string): string {
  const range = managedBlockRange(current);
  return range ? current.slice(range.start, range.end).trim() : "";
}

function managedBlockRange(current: string): { start: number; end: number } | null {
  const start = current.indexOf(BEGIN_MARKER);
  if (start < 0) {
    return null;
  }
  const endMarkerStart = current.indexOf(END_MARKER, start + BEGIN_MARKER.length);
  if (endMarkerStart < 0) {
    return null;
  }
  let end = endMarkerStart + END_MARKER.length;
  while (end < current.length && (current[end] === "\n" || current[end] === "\r")) {
    end += 1;
  }
  return { start, end };
}

function validateHostsLine(line: string): string | null {
  const trimmed = line.trim();
  if (trimmed.length === 0 || trimmed.startsWith("#")) {
    return null;
  }

  const tokens = trimmed.split(/\s+/).filter(Boolean);
  const commentStart = tokens.findIndex((token) => token.startsWith("#"));
  const fields = commentStart >= 0 ? tokens.slice(0, commentStart) : tokens;

  if (fields.length < 2) {
    return "Line must contain an IP address and at least one hostname.";
  }
  if (!isValidIpAddress(fields[0])) {
    return "Line must start with a valid IPv4 or IPv6 address.";
  }

  const invalid = fields.slice(1).find((hostname) => !isValidHostname(hostname));
  if (invalid) {
    return `Invalid hostname "${invalid}". Use letters, digits, dots, and hyphens.`;
  }

  return null;
}

function isValidIpAddress(value: string): boolean {
  return isValidIpv4(value) || isLikelyValidIpv6(value);
}

function isValidIpv4(value: string): boolean {
  const parts = value.split(".");
  return parts.length === 4 && parts.every((part) => {
    if (!/^\d+$/.test(part)) {
      return false;
    }
    const number = Number(part);
    return number >= 0 && number <= 255 && String(number) === part;
  });
}

function isLikelyValidIpv6(value: string): boolean {
  if (!value.includes(":")) {
    return false;
  }
  const normalized = value.toLowerCase();
  if (!/^[0-9a-f:.]+$/.test(normalized)) {
    return false;
  }
  try {
    new URL(`http://[${normalized}]/`);
    return true;
  } catch {
    return false;
  }
}

function isValidHostname(hostname: string): boolean {
  if (hostname.length === 0 || hostname.length > 253) {
    return false;
  }
  if (hostname === "localhost") {
    return true;
  }

  return hostname.split(".").every((label) => {
    return (
      label.length > 0 &&
      label.length <= 63 &&
      /^[A-Za-z0-9-]+$/.test(label) &&
      /^[A-Za-z0-9]/.test(label) &&
      /[A-Za-z0-9]$/.test(label)
    );
  });
}

function pushImportedNode(
  groups: AppState["groups"],
  groupName: string,
  nodeName: string | null,
  lines: string[],
) {
  const content = lines.join("\n").trim();
  if (content.length === 0) {
    return;
  }

  const node = {
    id: createId("node"),
    name: nodeName || "Imported Hosts",
    enabled: true,
    content,
  };
  const group = groups.find((candidate) => candidate.name === groupName);
  if (group) {
    group.nodes.push(node);
    return;
  }

  groups.push({
    id: createId("group"),
    name: groupName,
    nodes: [node],
  });
}

function createId(prefix: string) {
  if (typeof crypto !== "undefined" && "randomUUID" in crypto) {
    return `${prefix}-${crypto.randomUUID()}`;
  }
  return `${prefix}-${Date.now()}-${Math.random().toString(16).slice(2)}`;
}
